---
services:
  netbox:
    env_file:
      - development/dev.env
    build:
      context: .
      dockerfile: development/Dockerfile
    depends_on:
      - postgres
      - redis
      - redis-cache
    volumes:
      - ./development/configuration/plugins.py:/etc/netbox/config/plugins.py:z,ro
      - ./development/configuration/logging.py:/etc/netbox/config/logging.py:z,ro
      - ./development/demo-data.json:/tmp/demo-data.json:z,ro
      - ./:/source
    command: >
      sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
  # postgres
  postgres:
    image: postgres:18-alpine
    env_file:
      - development/dev.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # redis
  redis:
    image: redis:8-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file:
      - development/dev.env
  redis-cache:
    image: redis:8-alpine
    command:
      - sh
      - -c # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file:
      - development/dev.env
volumes:
  postgres-data:
