---
site_name: netbox-more-metrics
site_url: https://thedjvg.github.io/netbox-more-metrics
repo_url: https://github.com/TheDJVG/netbox-more-metrics
repo_name: TheDJVG/netbox-more-metrics
nav:
  - Home: index.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - "netbox_more_metrics"
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TheDJVG/netbox-more-metrics
      name: Github
    - icon: material/email
      link: "mailto:me+netbox@dj.vg"
