# Generated by Django 5.2.4 on 2025-07-30 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_more_metrics', '0004_metric_label_renames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='metriccollection',
            options={'ordering': ('name',)},
        ),
    ]
